name: 'gpr tool'
description: 'Run the gpr tool'
inputs:
  command:
    description: 'gpr command'
    required: false
    default: list
  token:
    description: 'PAT to use'
    required: false
    default: ${{ github.token }}
  path:
    description: 'Path to packages'
    required: true
  args:
    description: 'Any extra args'
    required: false
runs:
  using: "composite"
  steps: 
    - run: dotnet exec ${{ github.action_path }}/gpr.dll ${{ inputs.command }} ${{ inputs.path }} -k ${{ inputs.token }} ${{ inputs.args }}
      shell: bash
      env:
        DOTNET_NOLOGO: true
